[SERVER]
host = "localhost"
port = 3555
password = "helloworld!"

[IP]
blocks = ['2001:470:5521::/48', '1001:470:5521::/48']

[LOGGING]
path = "logs/"
backup_count = 5
max_bytes = 5242880  # 5mb

[LOGGING.LEVEL]
swish = "DEBUG"
discord = "NOTSET"
aiohttp = "NOTSET"
