[SERVER]
host = "127.0.0.1"
port = 8000
password = "helloworld!"

[IP]
blocks = []

[LOGGING]
path = "logs/"
backup_count = 5
max_bytes = 5242880  # 5mb

[LOGGING.LEVEL]
swish = "DEBUG"
discord = "NOTSET"
aiohttp = "NOTSET"
