[server]
host = "127.0.0.1"
port = 8000
password = "helloworld!"

[rotation]
enabled = false
method = "Banned"
blocks = []

[search]
max_results = 10

[logging]
path = "logs/"
backup_count = 5
max_bytes = 5242880

[logging.levels]
swish = "DEBUG"
actix = "OFF"
