name: Build

on:
  push:
  pull_request:
    types: [opened, edited]

jobs:
  Ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set Up CPython
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Deps
        run: |
          python -m ensurepip
          pip install setuptools
          pip install -r native/requirements-dev.txt
          pip install -r native/requirements.txt
          pip install -r requirements-dev.txt
          pip install -r requirements.txt

      - name: Build swish
        run: |
          python launcher.py --no-deps

  Windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set Up CPython
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Deps
        run: |
          python -m ensurepip
          pip install setuptools
          pip install -r native/requirements-dev.txt
          pip install -r native/requirements.txt
          pip install -r requirements-dev.txt
          pip install -r requirements.txt

      - name: Build swish
        run: |
          python launcher.py --no-deps

  MacOS:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set Up CPython
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Deps
        run: |
          python -m ensurepip
          pip install setuptools
          pip install -r native/requirements-dev.txt
          pip install -r native/requirements.txt
          pip install -r requirements-dev.txt
          pip install -r requirements.txt

      - name: Build swish
        run: |
          python launcher.py --no-deps