name: Build

on:
  push:
  pull_request:
    types: [opened, edited]

jobs:
  Ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set Up CPython
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Deps
        run: |
          sudo apt update
          sudo apt install -y libopus-dev
          python -m ensurepip
          pip install .[build]

      - name: Build swish
        run: |
          python build.py --no-deps

  Windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set Up CPython
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Deps
        run: |
          python -m ensurepip
          pip install .[build]

      - name: Build swish
        run: |
          python build.py --no-deps

  MacOS:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set Up CPython
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Deps
        run: |
          python -m ensurepip
          pip install .[build]

      - name: Build swish
        run: |
          python build.py --no-deps
