name: build-release

on: release
  types: [published]

jobs:
  Windows:
    runs-on: windows-latest

    steps:
      - name: Pull source
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Deps
        run: |
          python -m ensurepip
          pip install setuptools
          pip install -r native/requirements-dev.txt
          pip install -r native/requirements.txt
          pip install -r requirements-dev.txt
          pip install -r requirements.txt

      - name: Build swish
        run: |
          python build.py --no-deps

      - name: Upload binaries
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_path: ./dist/swish.exe
          asset_name: swish.exe
          asset_content_type: application/octet-stream

