name: Verify Types

on:
  push:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  Verify-Types:

    strategy:
      fail-fast: true
      matrix:
        python-version:
          - "3.10"

    name: "Python v${{ matrix.python-version }}"
    runs-on: ubuntu-latest

    steps:
      - name: "Initialise environment"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Setup Python v${{ matrix.python-version }}"
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: "Install dependencies"
        run: pip install .[build]

      - name: "Setup Node v16"
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: "Install pyright"
        run: npm install --location=global pyright

      - name: "Run pyright"
        run: pyright

      - name: "Verify Types"
        run: pyright --ignoreexternal --lib --verifytypes swish
